### ISSUE TITLE
Profile field to post link

### ISSUE THREAD

**Issue by luceos** [FriendsOfFlarum/masquerade#1]
Some field might be valid options to be shown on the Post card as link, eg a link to a website. We can easily inject these into the Post, next to like or so. We could then perhaps create a field type that allows donation/paying links and link these. As suggested by @bane_biddix https://discuss.flarum.org/d/5256-i-will-make-any-extension/110

**Comment by clarkwinkelmann** [comment]
Since many versions we can add links to the bio, which also shows in the user card.

I think that's close enough and we might as well close this issue instead of keeping it open forever :innocent:
