### ISSUE TITLE
Tab not showing up after activating

### ISSUE THREAD

**Issue by daylanKifky** [FriendsOfFlarum/masquerade#32]
Hi!
I'm trying to activate the extension in a relatively fresh installation of flarum. It doesn't give me any errors, not even in debug mode, but the masquerade Tab is not showing up.

**specs**:
Flarum 0.1.0-beta.8.1
PHP 7.2.10-0ubuntu0.18.04.1
MySQL 5.7.25-0ubuntu

**steps:**

- install with composer
- activate from admin panel

**Comment by Ralkage** [comment]
@daylanKifky there is no official Beta 8 release/update for this extension as of yet.

**Comment by kaspervm** [comment]
i am having the same problem. Is there a solution?

**Comment by daylanKifky** [comment]
Still not compatible with the beta8.
The best way to follow the development of these extensions is on the flarum discussion.

This is the masquerade thread:
https://discuss.flarum.org/d/5791-flagrow-masquerade-user-profile-builder

When a particular extension is not updated to work with the current version of flarum they are tagged as [incompatible]

**Comment by clarkwinkelmann** [comment]
Now compatible, I'm closing this issue.
