### ISSUE TITLE
No translation fallback and UI problem

### ISSUE THREAD

**Issue by paulmassen** [FriendsOfFlarum/masquerade#38]
Hi and thanks for the plugin.

I just started experimenting with Flarum in general, so correct me if flarum does not support translation fallback, but it looks like there is no translation fallback for this extension.

Also, it seems like there is an UI problem (see screenshot below).

![image](https://user-images.githubusercontent.com/12809352/61868614-07e40b80-aeda-11e9-8ca6-513248103ef3.png)

I will provide the translation for french users.
Thanks!

**Comment by luceos** [comment]
flarum currently does not support translation fallback, in addition none of the fof, flagrow or reflar teams are accepting any translations anymore, see https://discuss.flarum.org/d/19971

**Comment by paulmassen** [comment]
Oh, missed that thread. Good to know, thanks.

The UI problem is still valid though.

**Comment by clarkwinkelmann** [comment]
@paulmassen what is the UI problem on the screenshot ?

To edit them the fields must be extended by clicking on the field name. #37 will make this more obvious.

**Comment by paulmassen** [comment]
Yes, the UI problem on the screenshot is related to the legend (text and button) which is too high.

A transform:translateY(19px); seems to improve the location of the text: 

![image](https://user-images.githubusercontent.com/12809352/61871278-b7bc7780-aee0-11e9-8147-ba682d927e6e.png)

Also, it's a personal opition, but I think an Edit button would make more sense UX-wise.
Another problem is the fact that the background color is the same colour than the toggleable field set to "disabled". Thus, there is only a big white dot.

On the screenshot below, the background color is changed, and toggleable button is now visible:
![image](https://user-images.githubusercontent.com/12809352/61871655-a6279f80-aee1-11e9-918f-62ef4983a07f.png)

Hope it helps.

**Comment by clarkwinkelmann** [comment]
The positioning on the box border is intended, it mimics the default fieldset legend positioning of HTML forms.

This is how it will look once the other PR is merged:

![image](https://user-images.githubusercontent.com/5264300/61871844-23531480-aee2-11e9-94e0-093f32e1e104.png)

I don't deny the UI is still confusing. We're on a 3+ years old design here I think. I'd much prefer pulling the Mason components, but I don't have the time to do that anytime soon.

**Comment by paulmassen** [comment]
Ah, now I see why you positioned it like that. 

I think to make it more obvious for users (because I really thought there was a problem), you could have the text background set to white, to indicate that the text "belongs" to the field below and add a border to the box. 
In any case, I'm not sure a clickable legend next to an icon is good on an ux standpoint.

I will try to propose something.
Thanks for your answers and for the plugin.

**Comment by clarkwinkelmann** [comment]
The improvements from #37 have been published.

My idea in the long run would be to use the following design from Mason:

![image](https://user-images.githubusercontent.com/5264300/62010624-7d1b3f00-b16d-11e9-9a38-280562d0573d.png)

But this is probably not gonna happen anytime soon unless I can do it as part of a commissioned update. PR welcome though!

I suggest I close this issue, otherwise it might just stay open forever :innocent:

**Comment by paulmassen** [comment]
If it looks like the screenshot, this is great 👍
Thanks!
