### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by bet0x** [FriendsOfFlarum/masquerade#43]
After installing masquerade an adding a field i go to my profile and i complete the input. Then i go back to check the profile and i get a white page, with only the header menu.

**Comment by clarkwinkelmann** [comment]
Are you familiar with the browser javascript console ? Can you check if there is an error message there and copy-paste it ?

**Comment by bet0x** [comment]
```
Uncaught TypeError: Cannot read property 'children' of null
    at o (AddAttributes.js:31)
    at AddAttributes.js:37
    at Array.forEach (<anonymous>)
    at o (AddAttributes.js:36)
    at AddAttributes.js:37
    at Array.forEach (<anonymous>)
    at o (AddAttributes.js:36)
    at AddAttributes.js:37
    at Array.forEach (<anonymous>)
    at o (AddAttributes.js:36)
```
it's an error with the gamification plugin, seems they not compatible right?

**Comment by bet0x** [comment]
Well, several issues, not with Discord Auth after login i get an error. https://gyazo.com/2877a350b843c26db243834f30e9ea11

**Comment by clarkwinkelmann** [comment]
I tried replicating your issue without success.

Can you give more detailed steps to reproduce, ideally starting from a new blank Flarum install ?

Or if you only experience this on a specific forum, can you try disabling extensions until it works to identify with one causes a conflict ?

In your post from Oct 14, what indicates it has something to do with Gamification ? As far as I know, the two are compatible and I just installed both without seeing any issue.

Your post from Oct 15 doesn't seem related to this extension at all ?

**Comment by clarkwinkelmann** [comment]
I'm closing this issue. If you continue experiencing this, please reply and we'll reopen it.
