### ISSUE TITLE
Validation field too small for answers

### ISSUE THREAD

**Issue by andyg2** [FriendsOfFlarum/masquerade#47]
I have a country of origin drop down list however the validation field `varchar (255)` cannot hold the complete list of country names. I attempted to manually change the database field to `text` and manually populated the field however interface trims the data to 255 characters.
Would you consider changing the field type to something capable of holding a larger field set, or where could I look in the code to changing this manually.

**Comment by clarkwinkelmann** [comment]
I'm not sure if we want to change this...

The easiest solution for you is probably to change the type of the column in the database as you say, then manually enter the value in the database without going through Flarum admin. It won't be overwritten unless you edit that exact rule again from Flarum admin.

**Comment by andyg2** [comment]
> The easiest solution for you is probably to change the type of the column in the database

I understand not wanting to change that and you're are absolutely right, I've just discovered that the result in the admin interface was cached 🤦‍♂ 
Cache cleared and the manual edit of the validation field type to text gives me everything I need. Thank you.
